name: Testes automatizados do Lumen

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalando dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev python3-dev

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Criando ambiente virtual
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Instalando dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalando dependências JS
        run: npm install

      - name: Migrando
        run: |
          python manage.py makemigrations
          python manage.py migrate
      
      - name: Criando usuário de teste
        run: |
          python manage.py shell <<'PY'
          from django.contrib.auth import get_user_model
          User = get_user_model()
          username = "usuarioteste"
          email = "usuarioteste@example.com"
          password = "SenhaTeste123!"
          if not User.objects.filter(username=username).exists():
              User.objects.create_user(username=username, email=email, password=password)
              print("Usuário de teste criado")
          else:
              print("Usuário de teste já existe")
          PY

      - name: Testes do Cypress
        uses: cypress-io/github-action@v6
        with:
          start: python manage.py runserver
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 60

      - name: Tirando arquivos dos testes
        run: |
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress

  deploy:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalando dependências para migração
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodando migrações no banco de produção (Neon)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          DEBUG: 'False'
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Deploy para Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: .